language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
before_script:
  - sudo apt-get install astyle expect
  - mkdir src
  - find -maxdepth 1 -not -name src -not -name . -exec mv '{}' 'src/{}' \;
  - cd src
script: ant test
